networks:
  byond_net:
    driver: bridge

volumes:
  byond_mysql_data:
  byond-redis-data:

services:
  # -------------------------
  # MYSQL
  # -------------------------
  byond-mysql:
    image: mysql:8.0
    container_name: byond-mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - byond_mysql_data:/var/lib/mysql
    networks:
      - byond_net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-uroot', '-p${MYSQL_ROOT_PASSWORD}']
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'

  # -------------------------
  # REDIS
  # -------------------------
  byond-redis:
    image: redis:7-alpine
    container_name: byond-redis
    restart: unless-stopped
    volumes:
      - byond-redis-data:/data
    networks:
      - byond_net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'

  # -------------------------
  # PHPMYADMIN
  # -------------------------
  byond-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: byond-phpmyadmin
    restart: unless-stopped
    depends_on:
      byond-mysql:
        condition: service_healthy
    environment:
      PMA_HOST: byond-mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - byond_net
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'

  # -------------------------
  # BYOND API (NESTJS)
  # -------------------------
  byond-api:
    build: ./api
    container_name: byond-api
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: 3000
      DATABASE_HOST: byond-mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_NAME: byond
      REDIS_HOST: byond-redis
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - '${BYOND_API_PORT}:3000'
    depends_on:
      byond-mysql:
        condition: service_healthy
      byond-redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-uroot', '-p${MYSQL_ROOT_PASSWORD}']
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # MAIN WEBSITE (NEXTJS)
  # -------------------------
  main-website:
    build: ./website/main-website
    container_name: main-website
    restart: unless-stopped
    env_file: .env
    ports:
      - '${MAIN_WEBSITE_PORT}:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # BYOND ADMIN (VITE)
  # -------------------------
  byond-admin:
    build:
      context: ./admin
      args:
        VITE_API_BASE_URL: ${API_BASE_URL}
    container_name: byond-admin
    restart: unless-stopped
    env_file: .env
    ports:
      - '${BYOND_ADMIN_PORT}:80'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # RECRUITER PORTAL (VITE)
  # -------------------------
  recruiter-portal:
    build:
      context: ./portal/recruiter
      args:
        VITE_API_BASE_URL: ${API_BASE_URL}
    container_name: recruiter-portal
    restart: unless-stopped
    env_file: .env
    ports:
      - '${RECRUITER_PORTAL_PORT}:80'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # CANDIDATE PORTAL (NEXTJS)
  # -------------------------
  candidate-portal:
    build: ./portal/candidate
    container_name: candidate-portal
    restart: unless-stopped
    env_file: .env
    ports:
      - '${CANDIDATE_PORTAL_PORT}:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # APPMT API (PRISMA)
  # -------------------------
  appmt-api:
    build: ./appmt/appmt-api
    container_name: appmt-api
    restart: unless-stopped
    env_file: .env
    ports:
      - '${APPMT_API_PORT}:5000'
    depends_on:
      byond-mysql:
        condition: service_healthy
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # APPMT ADMIN (VITE)
  # -------------------------
  appmt-admin:
    build:
      context: ./appmt/appmt-admin
      args:
        VITE_API_BASE_URL: ${APPMT_API_BASE_URL}
    container_name: appmt-admin
    restart: unless-stopped
    ports:
      - '${APPMT_ADMIN_PORT}:80'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # APPMT PORTAL (VITE)
  # -------------------------
  appmt-portal:
    build:
      context: ./appmt/appmt-portal
      args:
        VITE_API_BASE_URL: ${APPMT_API_BASE_URL}
    container_name: appmt-portal
    restart: unless-stopped
    ports:
      - '${APPMT_PORTAL_PORT}:80'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net

  # -------------------------
  # RECRUITER WEBSITE (NEXTJS)
  # -------------------------
  recruiter-website:
    build: ./website/recruiter-website
    container_name: recruiter-website
    restart: unless-stopped
    ports:
      - '${RECRUITER_WEBSITE_PORT}:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '3'
    networks:
      - byond_net
